apiVersion: v1
kind: Pod
metadata:
  name: kiwi-secret-pod
  namespace: kiwi
spec:
  containers:
  - name: juicy
    image: nginx:1.7.9
    env:
    - name: USERKIWI
      valueFrom:
        secretKeyRef:
          name: juicysecret
          key: username
    - name: PASSKIWI
      valueFrom:
        secretKeyRef:
          name: juicysecret
          key: password
