apiVersion: v1
kind: Service
metadata:
  name: alta3
  namespace: dev
spec:
  selector:
    app: simpleservice
    role: dev
  ports:
  - name: simpleservice # No port is needed.
    port: 9876
    targetPort: 9876
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-simpleservice
  labels:
    app: simpleservice
    role: dev
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpleservice
      role: dev
  template:
    metadata:
      labels:
        app: simpleservice
        role: dev
    spec:
      containers:
      - image: mhausenblas/simpleservice:0.5.0
        name: simpleservice-dev
        ports:
        - name: simpleservice
          containerPort: 9876
          protocol: TCP
