apiVersion: batch/v1
kind: Job 
metadata:
  name: echocomplete
spec: 
  template:
    metadata:
      name: echocomplete
    spec:
      containers:
      - name: echo
        image: alpine:3.2
        command: ["/bin/sh"]
        args: ["-c", "echo hello; sleep 10"]
      restartPolicy: Never
