apiVersion: v1
kind: Namespace
metadata:
  name: kiwi
---
apiVersion: v1
kind: Pod
metadata:
  name: kiwi-secret-pod
  namespace: kiwi
spec:
  containers:
  - name: kiwi-secret-pod
    image: nginx:1.7.9
