apiVersion: v1
kind: Namespace
metadata:
  name: cherry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pit
  namespace: cherry
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pit
      version: v2
  template:
    metadata:
      labels:
        app: pit
        version: v2
    spec:
      containers:
      - name: pit-container
        image: nginx
        ports:
        - name: http
          containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stem
  namespace: cherry
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stem
      version: v2
  template:
    metadata:
      labels:
        app: stem
        version: v2
    spec:
      containers:
      - name: stem-container
        image: nginx
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pit-service
  namespace: cherry
spec:
  selector:
    app: pit
    version: v2
  ports:
  - name: pit
    port: 8080
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: stem-service
  namespace: cherry
spec:
  selector:
    app: stem
    version: v2
  ports:
  - name: stem
    port: 8080
    targetPort: 80
