apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cherry-control
  namespace: cherry
spec:
  podSelector:
    matchLabels:
      app: pit
      version: v2
  policyTypes:
    - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: stem
          version: v2
