apiVersion: v1
kind: Namespace
metadata:
  name: lincoln
---
apiVersion: v1
data:
  nginx.conf: |+
    user  nginx;
    worker_processes  1;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;
    events {
        worker_connections  1024;
    }
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
        access_log  /var/log/nginx/access.log  main;
        sendfile        on;
        keepalive_timeout  65;
        server {
            server_name  localhost;
            listen 80;
            root /var/www;

            location / {
              sendfile  on;
              index index.html;
            }
        }
    }

kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: lincoln
---
  apiVersion: v1
  data:
    index.html: |+
      <!DOCTYPE html>
      <html>
      <head>
      <title>K8s</title>
      <style>
          body {
              width: 35em;
              margin: 0 auto;
              font-family: Tahoma, Verdana, Arial, sans-serif;
          }
      </style>
      </head>
      <body>
      <h1>Welcome to K8s!</h1>
      <p>There is a mailbox here. To the north is a house.</p>
      <p>Open Mailbox</p>
      <p/There is a leaflet inside</p>
      <p>take leaflet</p>
      <p>Taken</p>
      <p>Read leaflet</p>
      <p>Welcome to the land of Kubernetes.</p>
      <p>No cloud should be without one!</p>

      <p><em>Thank you for using K8s.</em></p>
      <a href="/static/">Click to see static files (once they are configured)</a>
      <a href="/webby/"> Click to see webby (once it is configured)</a>
      </body>
      </html>

  kind: ConfigMap
  metadata:
    name: index-file
    namespace: lincoln
---
  apiVersion: v1
  data:
    nginx.txt: |
      It was a bright cold day in April, and the clocks were striking thirteen.
  kind: ConfigMap
  metadata:
    name: nginx-txt
    namespace: lincoln
---
apiVersion: v1
kind: Pod
metadata:
  name: vampire-hunter
  namespace: lincoln
  labels:
    app: nginx-configured
spec:
  containers:
  - name: nginx
    image: nginx:1.18.0
    ports:
    - name: chris
      containerPort: 80
    volumeMounts:
    - name: nginx-proxy-config
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf
    - name: my-index-file
      mountPath: /var/www/index.html
      subPath: index.html
    - name: static-demo-data
      mountPath: /var/www/static/nginx.txt
      subPath: nginx.txt
  volumes:
  - name: nginx-proxy-config
    configMap:
      name: nginx-conf
  - name: my-index-file
    configMap:
      name: index-file
  - name: static-demo-data
    configMap:
      name: nginx-txt
