apiVersion: batch/v1
kind: CronJob
metadata:
  name: kronos
  namespace: titans
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            fear: his-children
        spec:
          containers:
          - name: hunger
            image: busybox:1.28
            command: [/bin/sh, -c, 'sleep 2 && echo done']
          restartPolicy: OnFailure
