apiVersion: v1
kind: Namespace
metadata:
  name: mythical-creatures
---
apiVersion: v1
kind: Pod
metadata:
  name: manticore
  namespace: mythical-creatures
  labels:
    lion: "true"
    dragon: "true"
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
