apiVersion: batch/v1
kind: Job 
metadata:
  name: echocompletenocommand
spec: 
  template:
    metadata:
      name: echocompletenocommand
    spec:
      containers:
      - name: echo
        image: alpine:3.2
        ###command: ["/bin/sh"]
        ###args: ["-c", "echo hello; sleep 10"]
      restartPolicy: Never
