apiVersion: v1
kind: Service
metadata:
  name: sticky-service
spec:
  selector:
    matchLabels:
      sticky: deployment
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 600
  ports:
  - name: sticky-port
    port: 80
    targetPort: sticky-container-port
