apiVersion: v1
kind: ConfigMap
metadata:
  name: snooper-fluentd
  namespace: starfruit
data:
  fluentd.conf: |
    <source>
      type tail
      format none
      path /var/log/1.log
      pos_file /var/log/1.log.pos
      tag count.format1
    </source>

    <match **>
      @type stdout
    </match>
